---
title: "EFRI FINAL ANALYSIS"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
# Simulation Preparations
```{r Library}
rm(list=ls())
# install.packages("beepr")
# install.packages("plotly", dependencies=TRUE)
library(readxl)
library(tidyverse)
library(ggplot2)
library(plotly)
library(hrbrthemes)
library(viridis)
library(stringr)
library(beepr)
```

```{r Data Input}
getwd()
setwd("C:/Users/musta/Documents/R/R Projects/EFRI Policy")
dir()
path <- paste(getwd(),"/RECSData.xlsx", sep = "")

RECSData <- read_excel(path, sheet = "data")
```

```{r RECS Divisions}
# 1.   Pacific - 2.21 hrs
# 2.   West South Central - 
# 3.   East South Central -  
# 4.   West North Central - 3.12 hrs
# 5.   Middle Atlantic - 1.59 +  29.61/60 = 2.08 hrs
# 6.   New England - 1.76 (Colab)
# 7.   South Atlantic - 
# 8.   East North Central - 
# 9.   Mountain North - 1.89 (Colab)
# 10.  Mountain South - 
```

```{r Divisions}
division = unique(RECSData$DIVISION)[2]

EFRI_Input = RECSData %>% filter(RECSData$DIVISION == division)

h = EFRI_Input$NHSLDMEM # Number of residents in a household
i = EFRI_Input$MONEYPY # Annual income of a household
c = EFRI_Input$KWH # Annual electricity consumption of a household
p = mean(EFRI_Input$PRICE)/100 #Defining the electricity price of the selected region per KWh
m = EFRI_Input$NWEIGHT # Statistical multiplier for expressing how many households are represented by that survey

print(division)
```

```{r RAM Considerations}
paste("epr_limit:",trunc(sum(c * m) / sum(h * m)))
paste("eph_limit:",trunc(sum(c * m) / sum(m)))
cat("\n")
paste("total rows (million):",round(trunc(sum(c * m) / sum(h * m)) * trunc(sum(c * m) / sum(m)) /1000000, digits=1))
```

```{r Divide Simulation}
divider = 3
paste("eph_limit:",trunc(sum(c * m) / sum(m)))
eph_limit = trunc(sum(c * m) / sum(m))

paste(0,eph_limit/divider)
paste(eph_limit/divider+1,2*eph_limit/divider)
paste(2*eph_limit/divider+1,3*eph_limit/divider)
#paste(3*eph_limit/divider+1,4*eph_limit/divider)
print(division)
```

# Simulation Implementation
```{r EFRI Simulation Model}
EFRI = function(h,i,c,p,m=1,epov=0.1,epr=0,eph=0,savename="EFRI_Sim") {
  # h: Household size (Number of residents) - list of numbers
  # i: Annual income of a household - list of numbers
  # c: Annual electricity consumption of a household - list of numbers
  # p: Electricity price - numeric input (same unit as income)
  # m: Statistical multiplier (number of represented households by one household) - list of numbers
  # epov: energy poverty threshold (% of income)
  # epr: Free electricity per resident - numeric input
  # eph: Free electricity per household - numeric input
  
  start.time <- Sys.time()
  
  epr_limit = trunc(sum(c * m) / sum(h * m)) # Upper limit for free electricity  per resident (rounded down)
  eph_limit = trunc(sum(c * m) / sum(m)) # Upper limit for free electricity  per household (rounded down)
  
  datalist = list()
  counter = 1
  
  for(epr in 0:epr_limit) #epr_limit
  {
    for(eph in 0:4775) # eph_limit*** RAM Consideration: Divide simulations if necessary
    {
      if(sum(epr*h*m)+sum(eph*m) > sum(c * m)) {
        next # EFRI Constraint: Total free electricity amount cannot be more than total consumed electricity
      }
      rii_list = ((((sum((p*c)*m))/(sum((c-(pmin((epr*h+eph),c)))*m)))*((c-(pmin((epr*h+eph),c)))))/i)
      
      psim = sum((p*c)*m)/sum((c-(pmin((epr*h+eph),c)))*m)
      
      riiave = mean(rii_list) # Average Ratio in Income
      riiavelow = mean(rii_list[i<=quantile(i, probs=0.2)])
      
      riimed = median(rii_list) # Median Ratio in Income
      riimedlow = median(rii_list[i<=quantile(i, probs=0.2)])
      
      npr = sum(m[rii_list>=epov]*h[rii_list>=epov])
      nph = sum(m[rii_list>=epov])
      
      datalist [[counter]] = c(epr,eph,round(100*psim, digits = 2),round(100*riiave, digits = 2),round(100*riiavelow, digits = 2),round(100*riimed, digits = 2),round(100*riimedlow, digits = 2),round(npr, digits = 0),round(nph, digits = 0))
      counter = counter+1
    }
  }
  
  results = do.call(rbind, datalist)
  colnames(results) = c("EPR", "EPH","PSIM","RIIAVE","RIIAVELOW","RIIMED","RIIMEDLOW","NPR","NPH")
  
  EFRI_Sim <<- results
  
  end.time <- Sys.time()
  time.taken <- end.time - start.time
  print(paste("* Simulation Duration: ", round(time.taken, digits = 2)), quote=FALSE)
  print("** Simulation data is saved into 'EFRI_Sim' csv file at your current directory", quote=FALSE)
  
  csvpath <- paste(getwd(),"/", savename,".csv", sep = "") # Saving name ****************
  write.csv(EFRI_Sim, csvpath, row.names = FALSE)
}
```

```{r EFRI Run}
division
EFRI(h,i,c,p,m,epov=0.1,savename = paste(division,"-1", sep = ""))

beep(8) # Beep Sound when the simulation ends
```

# Preparing Analysis Tables
```{r CSV Save Name}
division
savename = division
```

```{r Append CSV Files}
getwd()
dir()

rm(csv1, csv2, csv3, csv4) # **************

csv1 = read.csv(paste(getwd(),"/Middle Atlantic -1.csv", sep = "")) # **************
csv2 = read.csv(paste(getwd(),"/Middle Atlantic -2.csv", sep = "")) # **************
#csv3 = read.csv(paste(getwd(),"/Middle Atlantic-3.csv", sep = "")) # **************
#csv4 = read.csv(paste(getwd(),"/Middle Atlantic-4.csv", sep = "")) # **************
rawdata = rbind(csv1,csv2) #,csv3,csv4) # **************

rawpath <- paste(getwd(),"/", savename, "_raw.csv", sep = "")
write.csv(rawdata, rawpath, row.names = FALSE)
beep(1) # Beep Sound when the appending ends
```

```{r Check Raw Data}
rm(rawdata)
rawdata = read.csv(rawpath)
summary(rawdata)
beep(1)
```

```{r Raw Data Patterns}
rawdata[0:1000,] %>%
  ggplot(aes(x=NPR, y=PSIM)) + 
  geom_point() +
  xlab("Average Electricity Share in Low Income Budgets") +
  ylab("Price of Electricity")
```

```{r Optimum Points}
normalizer <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

opt_init   = rawdata[which(rawdata$EPR == 0 & rawdata$EPH ==0),]
opt_ave    = rawdata[which.min(sqrt(normalizer(rawdata$RIIAVE)   ^2 + normalizer(rawdata$PSIM)^2)),]
opt_avelow = rawdata[which.min(sqrt(normalizer(rawdata$RIIAVELOW)^2 + normalizer(rawdata$PSIM)^2)),]
opt_med    = rawdata[which.min(sqrt(normalizer(rawdata$RIIMED)   ^2 + normalizer(rawdata$PSIM)^2)),]
opt_medlow = rawdata[which.min(sqrt(normalizer(rawdata$RIIMEDLOW)^2 + normalizer(rawdata$PSIM)^2)),]
opt_npr    = rawdata[which.min(sqrt(normalizer(rawdata$NPR)      ^2 + normalizer(rawdata$PSIM)^2)),]
opt_nph    = rawdata[which.min(sqrt(normalizer(rawdata$NPH)      ^2 + normalizer(rawdata$PSIM)^2)),]

#opt_npr    = rawdata[which.min(rawdata$NPR),]
#opt_nph    = rawdata[which.min(rawdata$NPH),]

opt_init   = cbind(opt_init,   Simulation = "INITIAL", Location = division)
opt_ave    = cbind(opt_ave,    Simulation = "RIIAVE", Location = division)
opt_avelow = cbind(opt_avelow, Simulation = "RIIAVELOW", Location = division)
opt_med    = cbind(opt_med,    Simulation = "RIIMED", Location = division)
opt_medlow = cbind(opt_medlow, Simulation = "RIIMEDLOW", Location = division)
opt_npr    = cbind(opt_npr,    Simulation = "NPR", Location = division)
opt_nph    = cbind(opt_nph,    Simulation = "NPH", Location = division)

optdata = rbind(opt_init, opt_ave,opt_avelow, opt_med, opt_medlow, opt_npr, opt_nph)

optpath = paste(getwd(),"/", savename, "_opt.csv", sep = "")
write.csv(optdata, optpath, row.names = FALSE)

```

```{r Aggregate Data}
# "EPR", "EPH","PSIM","RIIAVE","RIIAVELOW","RIIMED","RIIMEDLOW","NPR","NPH"

filter_ave    = aggregate(PSIM ~ RIIAVE,     data = rawdata, FUN = min)
filter_avelow = aggregate(PSIM ~ RIIAVELOW,  data = rawdata, FUN = min)
filter_med    = aggregate(PSIM ~ RIIMED,     data = rawdata, FUN = min)
filter_medlow = aggregate(PSIM ~ RIIMEDLOW,  data = rawdata, FUN = min)
filter_npr    = aggregate(PSIM ~ NPR,        data = rawdata, FUN = min)
filter_nph    = aggregate(PSIM ~ NPH,        data = rawdata, FUN = min)

# Less Data -
# agg_ave    = semi_join(rawdata, filter_ave,    by=c("RIIAVE" = "RIIAVE",       "PSIM"="PSIM"))
# agg_avelow = semi_join(rawdata, filter_avelow, by=c("RIIAVELOW" = "RIIAVELOW", "PSIM"="PSIM"))
# agg_med    = semi_join(rawdata, filter_med,    by=c("RIIMED" = "RIIMED",       "PSIM"="PSIM"))
# agg_medlow = semi_join(rawdata, filter_medlow, by=c("RIIMEDLOW" = "RIIMEDLOW", "PSIM"="PSIM"))
# agg_npr    = semi_join(rawdata, filter_npr,    by=c("NPR" = "NPR",             "PSIM"="PSIM"))
# agg_nph    = semi_join(rawdata, filter_nph,    by=c("NPH" = "NPH",             "PSIM"="PSIM"))

# More Data -
agg_ave    = rawdata %>%
            filter(rawdata$PSIM == filter_ave$PSIM    | rawdata$RIIAVE    == filter_ave$RIIAVE)
agg_avelow = rawdata %>% 
            filter(rawdata$PSIM == filter_avelow$PSIM | rawdata$RIIAVELOW == filter_avelow$RIIAVELOW)
agg_med    = rawdata %>% 
            filter(rawdata$PSIM == filter_med$PSIM    | rawdata$RIIMED    == filter_med$RIIMED)
agg_medlow = rawdata %>% 
            filter(rawdata$PSIM == filter_medlow$PSIM | rawdata$RIIMEDLOW == filter_medlow$RIIMEDLOW)
agg_npr    = rawdata %>% 
            filter(rawdata$PSIM == filter_npr$PSIM    | rawdata$NPR       == filter_npr$NPR)
agg_nph    = rawdata %>% 
            filter(rawdata$PSIM == filter_nph$PSIM    | rawdata$NPH       == filter_nph$NPH)

# More & More Data -
# agg_ave    = semi_join(rawdata, filter_ave,    by=c("PSIM"="PSIM"))
# agg_avelow = semi_join(rawdata, filter_avelow, by=c("PSIM"="PSIM"))
# agg_med    = semi_join(rawdata, filter_med,    by=c("PSIM"="PSIM"))
# agg_medlow = semi_join(rawdata, filter_medlow, by=c("PSIM"="PSIM"))
# agg_npr    = semi_join(rawdata, filter_npr,    by=c("PSIM"="PSIM"))
# agg_nph    = semi_join(rawdata, filter_nph,    by=c("PSIM"="PSIM"))


simdata = rbind(agg_ave,agg_avelow,agg_med,agg_medlow,agg_npr,agg_nph) %>% distinct()

simpath = paste(getwd(),"/", savename, "_sim.csv", sep = "")
write.csv(simdata, simpath, row.names = FALSE)

beep(1)
```

# Initial Analysis

```{r Data}
rm(list=ls())

getwd()

path <- paste(getwd(),"/RECSData.xlsx", sep = "")
RECSData <- read_excel(path, sheet = "data")

RECSData = cbind(RECSData,(RECSData$PRICE*RECSData$KWH)/RECSData$MONEYPY)
names(RECSData)[length(names(RECSData))]<-"RII"

RECSData$Group = str_wrap(RECSData$INCOMEGROUP, width = 12)

RECS_PAC = RECSData %>% filter(RECSData$DIVISION == "Pacific")
RECS_WSC = RECSData %>% filter(RECSData$DIVISION == "West South Central")
RECS_ESC = RECSData %>% filter(RECSData$DIVISION == "East South Central")
RECS_WNC = RECSData %>% filter(RECSData$DIVISION == "West North Central")
RECS_MIA = RECSData %>% filter(RECSData$DIVISION == "Middle Atlantic")
RECS_SOA = RECSData %>% filter(RECSData$DIVISION == "South Atlantic")
RECS_ENC = RECSData %>% filter(RECSData$DIVISION == "East North Central")
RECS_MON = RECSData %>% filter(RECSData$DIVISION == "Mountain North")
RECS_MOS = RECSData %>% filter(RECSData$DIVISION == "Mountain South")
```

```{r Location Selection}
RECS_Analysis = RECS_MIA
selectedregion = "Middle Atlantic"
```

```{r Region BoxPlot}
RECS_Analysis %>%
  ggplot( aes(x=Group, y=RII, fill=Group)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
  #theme_ipsum() +
  theme(axis.text.x = element_text(size=10),
        legend.position="none",
        plot.title = element_text(size=11)
  ) +
  ggtitle("Seleted Region by Income Level ") + # **********************
  xlab("")+
  ylab("Electricity Budget Ratio in Income")+
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60))+ 
  coord_flip()+
  scale_y_continuous(limit = c(0, 30))
```

# Simulated Data & Plots

```{r Simulated Data}
simdata = read.csv(file = paste(getwd(),"/Results/",selectedregion,"_sim.csv", sep = ""))
optdata = read.csv(file = paste(getwd(),"/Results/",selectedregion,"_opt.csv", sep = ""))
```

```{r Plot - EPR vs EPH by Price}
simdata %>%
  ggplot(aes(x=EPR, y=EPH, color=PSIM)) + 
  geom_point() +
  scale_color_gradient(low="gray", high="firebrick3") +
  xlab("Free Electricity per Resident") +
  ylab("Free Electricity per Household") +
  ggtitle("Free Electricity Amounts by Electricity Price")+
  geom_point(data=optdata[2:7,], 
             aes(x=EPR,y=EPH, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=EPR,y=EPH),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - EPR vs EPH by NPH}
simdata %>%
  ggplot(aes(x=EPR, y=EPH, color=NPH)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Free Electricity per Resident") +
  ylab("Free Electricity per Household") +
  ggtitle("Free Electricity Amounts by #EPOV Households")+
  geom_point(data=optdata[2:7,], 
             aes(x=EPR,y=EPH, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=EPR,y=EPH),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - EPR vs EPH by NPR}
simdata %>%
  ggplot(aes(x=EPR, y=EPH, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Free Electricity per Resident") +
  ylab("Free Electricity per Household") +
  ggtitle("Free Electricity Amounts by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=EPR,y=EPH, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=EPR,y=EPH),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs RIIAVE}
simdata %>%
  ggplot(aes(x=PSIM, y=RIIAVE, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Average Ratio in Income of All Households") +
  ggtitle("Average RII vs Electricity Price by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=RIIAVE, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=RIIAVE),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs RIIAVELOW}
simdata %>%
  ggplot(aes(x=PSIM, y=RIIAVELOW, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Average Ratio in Income of Low-Income Households") +
  ggtitle("Low-Income Average RII vs Electricity Price by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=RIIAVELOW, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=RIIAVELOW),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs RIIMED}
simdata %>%
  ggplot(aes(x=PSIM, y=RIIMED, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Median Ratio in Income of All Households") +
  ggtitle("Median RII vs Electricity Price by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=RIIMED, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=RIIMED),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs RIIMEDLOW}
simdata %>%
  ggplot(aes(x=PSIM, y=RIIMEDLOW, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Median Ratio in Income of Low-Income Households") +
  ggtitle("Low-Income Median RII vs Electricity Price by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=RIIMEDLOW, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=RIIMEDLOW),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs NPH}
simdata %>%
  ggplot(aes(x=PSIM, y=NPH, color=NPH)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Number of Households Suffering From Energy Poverty") +
  ggtitle("#EPOV Households vs Electricity Price by #EPOV Households")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=NPH, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=NPH),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - Price vs NPR}
simdata %>%
  ggplot(aes(x=PSIM, y=NPR, color=NPR)) + 
  geom_point() +
  scale_color_gradient(low="turquoise", high="firebrick3") +
  xlab("Unit Price of Electricity") +
  ylab("Number of Residents Suffering From Energy Poverty") +
  ggtitle("#EPOV Residents vs Electricity Price by #EPOV Residents")+
  geom_point(data=optdata[2:7,], 
             aes(x=PSIM,y=NPR, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=PSIM,y=NPR),  
             color= "black", shape=1,
             size=3)
```

```{r Plot - NPH vs NPR}
simdata %>%
  ggplot(aes(x=NPH, y=NPR, color=PSIM)) + 
  geom_point() +
  scale_color_gradient(low="gray", high="firebrick3") +
  xlab("Number of Households Suffering From Energy Poverty") +
  ylab("Number of Residents Suffering From Energy Poverty") +
  ggtitle("#EPOV Households vs #EPOV Residents by Electricity Price")+
  geom_point(data=optdata[2:7,], 
             aes(x=NPH,y=NPR, shape= Simulation), 
             color= "black", 
             size=3) +
  geom_point(data=optdata[1,], 
             aes(x=NPH,y=NPR),  
             color= "black", shape=1,
             size=3)
```

```{r 3D Plot}
sim3d = plot_ly(simdata, x = ~EPR, y = ~EPH, z = ~PSIM,
                         marker = list(color = ~NPR, colorscale = c('#FFE1A1', '#683531'), showscale = TRUE))
sim3d = sim3d %>% add_markers()
sim3d = sim3d %>% layout(scene = list(xaxis = list(title = 'Free Electricity per Resident'),
                                             yaxis = list(title = 'Free Electricity per Household'),
                                             zaxis = list(title = 'Electricity Unit Price')),
                                annotations = list(
                                  x = 1.13,
                                  y = 1.05,
                                  text = '# People Suffering From EPOV',
                                  xref = 'paper',
                                  yref = 'paper',
                                  showarrow = FALSE
                                ))

sim3d
```

# Simulated Comparisons

```{r Input}
# CASE ---
# 1: INITIAL
# 2: RIIAVE
# 3: RIIAVELOW
# 4: RIIMED
# 5: RIIMEDLOW
# 6: NPR
# 7: NPH

case = 6

EPR = optdata[case,"EPR"]
EPH = optdata[case,"EPH"]
PRICEsim = optdata[case,"PSIM"]

optdata

EPR
EPH
PRICEsim
```

```{r Cbinds}
rm(RECS_Analysis_plot)
RECS_Analysis_plot = cbind(RECS_Analysis,PRICEsim)
  names(RECS_Analysis_plot)[length(names(RECS_Analysis_plot))]<-"PRICEsim"
  
RECS_Analysis_plot = cbind(RECS_Analysis_plot,EPR*RECS_Analysis_plot$NHSLDMEM + EPH)
  names(RECS_Analysis_plot)[length(names(RECS_Analysis_plot))]<-"KWHgrant"
  
  RECS_Analysis_plot = cbind(RECS_Analysis_plot,pmin(RECS_Analysis_plot$KWHgrant,RECS_Analysis_plot$KWH))
 names(RECS_Analysis_plot)[length(names(RECS_Analysis_plot))]<-"KWHgrcons"
  
 RECS_Analysis_plot = cbind(RECS_Analysis_plot,RECS_Analysis_plot$KWH - RECS_Analysis_plot$KWHgrcons)
 names(RECS_Analysis_plot)[length(names(RECS_Analysis_plot))]<-"KWHpaid"

 RECS_Analysis_plot = cbind(RECS_Analysis_plot,(RECS_Analysis_plot$PRICEsim*RECS_Analysis_plot$KWHpaid)/RECS_Analysis_plot$MONEYPY)
 names(RECS_Analysis_plot)[length(names(RECS_Analysis_plot))]<-"RIIsim"
```

```{r Plots}
RECS_Analysis_plot %>%
   ggplot( aes(x=Group, y=RIIsim, fill=Group)) +
   geom_boxplot() +
   scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
   theme_get() +
   theme(axis.text.x = element_text(size=10),
         legend.position="none",
         plot.title = element_text(size=11)
   ) +
   ggtitle("Selected Region by Income Level ") + # *************
   xlab("")+
   ylab("Electricity Budget Ratio in Income")+
   scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60))+ 
   coord_flip()+
 scale_y_continuous(limit = c(0, 30))
```

```{r Initial vs Simulated}
   a_ = RECS_Analysis_plot[,"INCOMEGROUP"] %>% cbind(RECS_Analysis_plot[,"RII"], rep("Initial Case",nrow(RECS_Analysis_plot))) 
   b_ = RECS_Analysis_plot[,"INCOMEGROUP"] %>% cbind(RECS_Analysis_plot[,"RIIsim"], rep("Simulated Case",nrow(RECS_Analysis_plot))) 
   comparisonplot = data.frame(rbind(a_,b_))
   
   comparisonplot[,2] = as.numeric(comparisonplot[,2])
   colnames(comparisonplot) = c("Group","RII","Case")
   
   
    comparisonplot %>%
     ggplot( aes(x=Group, y=RII, fill=Case)) +
     geom_boxplot() +
     facet_wrap(~Group, scale="free") +
     scale_fill_manual(values = c("grey", "turquoise")) +
     theme_get() +
     #theme_ipsum() +
     theme(axis.text.x = element_text(size=10),
           axis.text.y = element_blank(),
           legend.position=c(0.83,0.2),
           legend.title = element_blank(),
           legend.text = element_text(size=11),
           plot.title = element_text(size=12)
     ) +
    scale_shape_manual(values= c(1,19)) +
     ggtitle("Initial vs Simulated Ratio in Income by Income Levels") + #************
     xlab("")+
     ylab("Electricity Cost Ratio in Total Income of a Household")+
     #scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60))+
     coord_flip()
     #scale_y_continuous(limit = c(0, 60))
```

# Comparison Report

```{r Comparison Report}

RECS_LowIncome = RECS_Analysis_plot %>% filter(MONEYPY <= quantile(MONEYPY, probs=0.2)) 

```

```{r #EPOV Residents}
EPOV_init = RECS_Analysis_plot %>% filter(RII>=10)
EPOV_init_total = sum(EPOV_init$NWEIGHT*EPOV_init$NHSLDMEM)

EPOV_sim = RECS_Analysis_plot %>% filter(RIIsim>=10)
EPOV_sim_total = sum(EPOV_sim$NWEIGHT*EPOV_sim$NHSLDMEM)

print("COMPARISON: Number of Total Energy Poor Residents")

print(paste("Initial Case:",round(EPOV_init_total, digits=0)))
print(paste("Simulated Case:",round(EPOV_sim_total, digits=0)))
print(paste("Difference (Number of Residents):",round(EPOV_init_total - EPOV_sim_total, digits=0)))
print(paste("Improvement (Number of Residents): %",100*round((EPOV_init_total - EPOV_sim_total)/EPOV_init_total, digits=4)))

```

```{r #EPOV Residents without Energy Assistance}

EPOV_init = RECS_Analysis_plot %>% filter(RII>=10 & ENERGYASST==0)
EPOV_init_total = sum(EPOV_init$NWEIGHT*EPOV_init$NHSLDMEM)

EPOV_sim = RECS_Analysis_plot %>% filter(RIIsim>=10 & ENERGYASST==0)
EPOV_sim_total = sum(EPOV_sim$NWEIGHT*EPOV_sim$NHSLDMEM)

print("COMPARISON: Number of Total Energy Poor Residents without Energy Assistance")

print(paste("Initial Case:",round(EPOV_init_total, digits=0)))
print(paste("Simulated Case:",round(EPOV_sim_total, digits=0)))
print(paste("Difference (Number of Residents):",round(EPOV_init_total - EPOV_sim_total, digits=0)))
print(paste("Improvement (Number of Residents): %",100*round((EPOV_init_total - EPOV_sim_total)/EPOV_init_total, digits=4)))

```

```{r #EPOV Low-Income Residents}

EPOV_init = RECS_LowIncome %>% filter(RII>=10)
EPOV_init_total = sum(EPOV_init$NWEIGHT*EPOV_init$NHSLDMEM)


EPOV_sim = RECS_LowIncome %>% filter(RIIsim>=10)
EPOV_sim_total = sum(EPOV_sim$NWEIGHT*EPOV_sim$NHSLDMEM)

print("COMPARISON: Number of Energy Poor Low-Income Residents")

print(paste("Initial Case:",round(EPOV_init_total, digits=0)))
print(paste("Simulated Case:",round(EPOV_sim_total, digits=0)))
print(paste("Difference (Number of Residents):",round(EPOV_init_total - EPOV_sim_total, digits=0)))
print(paste("Improvement (Number of Residents): %",100*round((EPOV_init_total - EPOV_sim_total)/EPOV_init_total, digits=4)))

```


```{r #EPOV Low-Income Residents without Energy Assistance}

EPOV_init = RECS_LowIncome %>% filter(RII>=10 & ENERGYASST==0)
EPOV_init_total = sum(EPOV_init$NWEIGHT*EPOV_init$NHSLDMEM)

EPOV_sim = RECS_LowIncome %>% filter(RIIsim>=10 & ENERGYASST==0)
EPOV_sim_total = sum(EPOV_sim$NWEIGHT*EPOV_sim$NHSLDMEM)

print("COMPARISON: Number of Energy Poor Low-Income Residents without Energy Assistance")

print(paste("Initial Case:",round(EPOV_init_total, digits=0)))
print(paste("Simulated Case:",round(EPOV_sim_total, digits=0)))
print(paste("Difference (Number of Residents):",round(EPOV_init_total - EPOV_sim_total, digits=0)))
print(paste("Improvement (Number of Residents): %",100*round((EPOV_init_total - EPOV_sim_total)/EPOV_init_total, digits=4)))

```

